/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package singletonpattern;

import javafx.scene.paint.Color;
import javax.swing.JOptionPane;
/**
 *
 * @author Mickael Walter
 */
public class Withdraw extends javax.swing.JFrame {

    /**
     * Creates new form Withdraw
     */
    public Withdraw() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        instructLabel = new javax.swing.JLabel();
        BTN20 = new javax.swing.JButton();
        BTN40 = new javax.swing.JButton();
        BTN100 = new javax.swing.JButton();
        cashBTN = new javax.swing.JButton();
        txtOther = new javax.swing.JTextField();
        LBLOther = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        instructLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 22)); // NOI18N
        instructLabel.setText("Select withdrawal amount and press <CASH OUT>");

        BTN20.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        BTN20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/singletonpattern/icons8-us-dollar-24.png"))); // NOI18N
        BTN20.setText("20.00");
        BTN20.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BTN20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTN20MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BTN20MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BTN20MouseExited(evt);
            }
        });

        BTN40.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        BTN40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/singletonpattern/icons8-us-dollar-24.png"))); // NOI18N
        BTN40.setText("40.00");
        BTN40.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BTN40.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTN40MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BTN40MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BTN40MouseExited(evt);
            }
        });

        BTN100.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        BTN100.setIcon(new javax.swing.ImageIcon(getClass().getResource("/singletonpattern/icons8-us-dollar-24.png"))); // NOI18N
        BTN100.setText("100.00");
        BTN100.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BTN100.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTN100MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BTN100MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BTN100MouseExited(evt);
            }
        });

        cashBTN.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        cashBTN.setForeground(new java.awt.Color(0, 153, 153));
        cashBTN.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mickael Walter\\Google Drive USC\\YEAR 4 - 2020_2021\\Semester 1 - Sep_Dec.2020\\CPTR427 - Object Oriented Design & Programming\\OODP Programes\\SingletonPattern\\money.png")); // NOI18N
        cashBTN.setText("Cash Out");
        cashBTN.setBorder(null);
        cashBTN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cashBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cashBTNMouseClicked(evt);
            }
        });

        txtOther.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        txtOther.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtOther.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        LBLOther.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        LBLOther.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LBLOther.setIcon(new javax.swing.ImageIcon(getClass().getResource("/singletonpattern/icons8-us-dollar-24.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(BTN20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BTN40)
                .addGap(120, 120, 120))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(BTN100)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LBLOther, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtOther, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(instructLabel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(cashBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(instructLabel)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTN20)
                    .addComponent(BTN40))
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LBLOther, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(BTN100)
                        .addComponent(txtOther, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(cashBTN)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    double cashRemoved; //Global Variable
    
    private void BTN20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTN20MouseClicked
        cashRemoved = Double.parseDouble(BTN20.getText() );
        Singleton.getInstance().withdraw(cashRemoved);
    }//GEN-LAST:event_BTN20MouseClicked

    private void cashBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cashBTNMouseClicked
        if (txtOther != null) {
            try {
                cashRemoved = Double.parseDouble(txtOther.getText() );
                Singleton.getInstance().withdraw(cashRemoved);
            } catch (Exception e) {
                //It works...
            }
        }
        
        JOptionPane.showMessageDialog(this,  "Successful transaction. Remaining balance 💲 "
        + Singleton.getInstance().getBalance());
    }//GEN-LAST:event_cashBTNMouseClicked

    private void BTN40MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTN40MouseClicked
        cashRemoved = Double.parseDouble(BTN40.getText() );
        Singleton.getInstance().withdraw(cashRemoved);
    }//GEN-LAST:event_BTN40MouseClicked

    private void BTN100MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTN100MouseClicked
        cashRemoved = Double.parseDouble(BTN100.getText() );
        Singleton.getInstance().withdraw(cashRemoved);
    }//GEN-LAST:event_BTN100MouseClicked

    private void BTN20MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTN20MouseEntered
        BTN20.setForeground(java.awt.Color.red);
    }//GEN-LAST:event_BTN20MouseEntered

    private void BTN20MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTN20MouseExited
        BTN20.setForeground(java.awt.Color.BLACK);
    }//GEN-LAST:event_BTN20MouseExited

    private void BTN40MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTN40MouseEntered
        BTN40.setForeground(java.awt.Color.red);
    }//GEN-LAST:event_BTN40MouseEntered

    private void BTN40MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTN40MouseExited
        BTN40.setForeground(java.awt.Color.BLACK);
    }//GEN-LAST:event_BTN40MouseExited

    private void BTN100MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTN100MouseEntered
        BTN100.setForeground(java.awt.Color.red);
    }//GEN-LAST:event_BTN100MouseEntered

    private void BTN100MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTN100MouseExited
        BTN100.setForeground(java.awt.Color.BLACK);
    }//GEN-LAST:event_BTN100MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Withdraw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Withdraw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Withdraw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Withdraw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Withdraw().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN100;
    private javax.swing.JButton BTN20;
    private javax.swing.JButton BTN40;
    private javax.swing.JLabel LBLOther;
    private javax.swing.JButton cashBTN;
    private javax.swing.JLabel instructLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtOther;
    // End of variables declaration//GEN-END:variables
}
